name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:  # 添加权限设置
      contents: write  # 允许写入内容
      issues: write  # 允许写入问题
      pull-requests: write  # 允许写入拉取请求

    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
    
      - name: Install dependencies
        run: pnpm install

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1
        with:
          skip-upload: true
          skip-deploy: true
          bundle-command: pnpm bundle
          # store-endpoint: ${{ secrets.STORE_ENDPOINT }}
          # store-access-token: ${{ secrets.STORE_ACCESS_TOKEN }}
          # server-endpoint: ${{ secrets.SERVER_ENDPOINT }}
          # server-access-key: ${{ secrets.SERVER_ACCESS_KEY }}
          # server-access-secret: ${{ secrets.SERVER_ACCESS_SECRET }}
          # slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
